#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
chapter="${1:-1}"

exec "$repo_root/writing-a-c-compiler-tests/test_compiler" \
  "$repo_root/scripts/mycc" \
  --chapter "$chapter" \
  # --stage "$stage" \
  --latest-only \
  -f
